services:
    web:
        image: "ghcr.io/eliasb-nu/rcj-gamesite:${GIT_COMMIT_HASH:-latest}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.web.loadbalancer.server.port=80"
            - "traefik.http.routers.web.rule=Host(`rcjv.braunelias.com`)"
            - "traefik.http.routers.web.entrypoints=websecure"
            - "traefik.http.routers.web.tls.certresolver=cfACME"
