services:
    traefik:
        image: traefik:v3.1
        command:
            - "--providers.docker"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.websecure.address=:443"
            - "--certificatesresolvers.cfACME.acme.dnschallenge=true"
            - "--certificatesresolvers.cfACME.acme.dnschallenge.provider=cloudflare"
            - "--certificatesresolvers.cfACME.acme.email=braunelias@tghd.email"
            - "--certificatesresolvers.cfACME.acme.storage=/letsencrypt/acme.json"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        environment:
            - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
        ports:
            - mode: host
              protocol: tcp
              published: 80
              target: 80
            - mode: host
              protocol: tcp
              published: 443
              target: 443
        volumes:
            - letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock


    web:
        image: "ghcr.io/eliasb-nu/rcj-gamesite:${GIT_COMMIT_HASH:-latest}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.web.loadbalancer.server.port=3000"
            - "traefik.http.routers.web.rule=Host(`rcjv.braunelias.com`)"
            - "traefik.http.routers.web.entrypoints=websecure"
            - "traefik.http.routers.web.tls.certresolver=cfACME"
        ports:
        - "3000:3000"

volumes:
    letsencrypt: